---

services:
  reverse-proxy:
    image: caddy:2.9-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ../react-cdn
      dockerfile: docker/Dockerfile
      target: node_prod
      args:
        - NODE_PORT=${NODE_PORT:-5173}
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-3000}:${NGINX_PORT:-3000}"
    environment:
      - NGINX_PORT=${NGINX_PORT:-3000}

  backend:
    build:
      context: ../go-cdn
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    networks:
      - mongonet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=tribes
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      mongo:
        condition: service_healthy
    volumes: 
      - mongo-data:/data/db
    networks:
      - mongonet

volumes:
  caddy_data:
  caddy_config:
  mongo-data:
networks:
  mongonet:
    driver: 'bridge'