apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-cdn
  template:
    metadata:
      labels:
        app: go-cdn
    spec:
      containers:
        - name: go-cdn
          image: go-cdn:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: go-cdn-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-cdn
spec:
  selector:
    app: go-cdn
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
