apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-cdn
  template:
    metadata:
      labels:
        app: react-cdn
    spec:
      containers:
        - name: react-cdn
          image: react-cdn:latest
          ports:
            - containerPort: 3000
          env:
            - name: NGINX_PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: react-cdn
spec:
  selector:
    app: react-cdn
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
